### ISSUE TITLE
Device removed: SIGMACHIP USB Keyboard

### ISSUE THREAD

**Issue by samrayleung** [mooz/xkeysnail#11]
Hey Mr. Mooz, I have a werid issue. As title, sometimes when I just stop typing for a while, xkeysnail will say:
```
Device removed: SIGMACHIP USB Keyboard
```
But my USE keyboard hasn't been removed, then xkeysnail just doesn't work. So I just restart xkeysnail, and it works again. I have no idea how to sovle this issue!
Environment information:
OS: Arch Linux
WM: i3wm

**Comment by Lenbok** [comment]
I had a similar thing where my keyboard would occasionally be removed and re-added - this was at the kernel level according to dmesg, so it wasn't directly an xkeysnail issue.

Anyway, now that device re-adding has been implemented this should no longer be a problem, since you don't need to restart xkeysnail for things to back into a working state.

(This issue could probably be closed).
